name: 'publish'

on:
  push:
    branches:
      - master

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - name: Install vsce
        run: npm i -g vsce

      - name: Generate package
        run: vsce package

      - name: Publish
        run: vsce publish -p ${{secrets.VSCE_TOKEN}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
